apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: workshop
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db