apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: your_image_name:latest
        ports:
        - containerPort: 3000
        env:
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_KEY
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: CLOUDINARY_KEY
        - name: CLOUDINARY_SECRET
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: CLOUDINARY_SECRET
        - name: MAPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: MAPBOX_TOKEN
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: DB_URL
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
